### ISSUE TITLE
Support for JSX?

### ISSUE THREAD

**Issue by globexdesigns** [cfjedimaster/brackets-jshint#61]
Hey cfjedimaster,

I recently created a clone of brackets-jshint to add support for React.js JSX files (https://github.com/globexdesigns/brackets-jsxhint). The code is almost identical to brackets-jshint, but with with 10 new lines and React.js' JSXTransformer.js file. Which leads me to wonder... would it be better if I created a pull request here to merge that feature in? Or should your extension only focus on Javascript files?

I'm a little torn, because having a bunch of very similar linting extensions in Brackets feels frustrating to users and difficult to maintain for developers, but on the other hard, having JSX support in a JSHint extension might be beyond its original intent.

What do you think?

**Comment by ringzhz** [comment]
I vote yes! Support for JSX!!!!!

**Comment by globexdesigns** [comment]
I'm closing this as I've moved to using ESlint which has support for custom parsers. The combination of ESLint + Babel-Eslint provides full support JSX.
