### ISSUE TITLE
"JSHint has timed out after waiting for 10000 ms"

### ISSUE THREAD

**Issue by catdad** [cfjedimaster/brackets-jshint#81]
In the latest version, 2.2.16, I get this error for every file that I try to lint. Reverting back to 2.2.15 lints all of the same files just fine (and super quickly).

Running in the following Brackets version: `Release 1.3 build 1.3.0-16022 (release cd0a6aae5)`

**Comment by cfjedimaster** [comment]
Weird - it works for me - lets see if someone else sees this.

On Mon, Jun 1, 2015 at 7:48 AM, Kiril Vatev <notifications@github.com>
wrote:

> In the latest version, 2.2.16, I get this error for every file that I try
> to lint. Reverting back to 2.2.15 lints all of the same files just fine
> (and super quickly).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/brackets-jshint/issues/81>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by catdad** [comment]
Could this be something specific to my `.bracket.json`, `.jshintrc`, or '.jshintignore` files? Or just the fact that I am using those files?

**Comment by catdad** [comment]
The answer to that is no. I started a new project with a single (almost empty) js file and no config files. JSLint reports errors just fine, but JSHint times out.

Let me know if there's any info I could provide.

**Comment by cfjedimaster** [comment]
Did you try opening the console to see if something shows up there?

On Mon, Jun 1, 2015 at 8:08 AM, Kiril Vatev <notifications@github.com>
wrote:

> The answer to that is no. I started a new project with a single (almost
> empty) js file and no config files. JSLint reports errors just fine, but
> JSHint times out.
>
> Let me know if there's any info I could provide.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/brackets-jshint/issues/81#issuecomment-107443482>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by catdad** [comment]
Aha! I keep forgetting that opening the console no longer crashes Brackets.

Line 82 of main.js (in the JSHint extension), `$.extend({}, defaultConfig.globals, config.globals));`, has an error of `undefined is not a function`. After about a minute of looking into it, it seems that `JSHINT` is undefined.

Looking a bit higher up, I am also seeing that jshint.js:15363 has an `undefined is not a function`, which I believe is the first use of underscore inside JSHint... so JSHint is never actually initializing itself.

I don't have any more time now, but I can look into it more later in the afternoon if this does not provide anything helpful.

**Comment by JohnMarkT** [comment]
I'm seeing the same error: JSHint has timed out after waiting for 10000 ms

**Comment by redmunds** [comment]
I'm also seeing this problem with latest update on Win7. Same errors in console log as [here](https://github.com/cfjedimaster/brackets-jshint/issues/81#issuecomment-107501982).

**Comment by catdad** [comment]
I had a few coworkers check

**Comment by cfjedimaster** [comment]
Ah, I'm OSX. So why would it happen on Windows and not OSX??

**Comment by cfjedimaster** [comment]
Hey, what version of Brackets are yall on - latest? I'm 1.3.0.

**Comment by redmunds** [comment]
I'm seeing it on v1.3.0 installed version.

**Comment by cfjedimaster** [comment]
Oh - I've got a Windows machine now - let me test.

**Comment by JohnMarkT** [comment]
Brackets
Release 1.3 build 1.3.0-16022 (release cd0a6aae5) 
build timestamp: Fri Apr 24 2015 09:59:57 GMT+0100

Windows 8.1 Enterprise (64-bit)

**Comment by cfjedimaster** [comment]
Yeah, confirmed there.

**Comment by cfjedimaster** [comment]
So if Underscore is missing - is it maybe in the OSX Brackets but not Windows?

**Comment by redmunds** [comment]
I'm seeing same error on OSX. Maybe you have Underscore installed for some other extension?

**Comment by cfjedimaster** [comment]
Ahh - good point! So in theory if I just include my own copy of Underscore
I may be ok.

On Mon, Jun 1, 2015 at 10:28 AM, Randy Edmunds <notifications@github.com>
wrote:

> I'm seeing same error on OSX. Maybe you have Underscore installed for some
> other extension?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/brackets-jshint/issues/81#issuecomment-107583919>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by JohnMarkT** [comment]
Could you use native forEach instead?

**Comment by cfjedimaster** [comment]
Isn't the issue in JSHint? I don't want to mod it.

On Mon, Jun 1, 2015 at 10:44 AM, JohnMarkT <notifications@github.com> wrote:

> Could you use native forEach instead?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/brackets-jshint/issues/81#issuecomment-107596756>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by JohnMarkT** [comment]
Ahh -- got ya. I also realized forEach only works on arrays.

**Comment by catdad** [comment]
The issue is indeed in the jshint.js file. However, I am seeing a copy of lodash 3.6.0 in that file, loaded through a module loader (browserify, my guess).

**Comment by cfjedimaster** [comment]
This looks to be it: https://github.com/jshint/jshint/issues/2330

**Comment by cfjedimaster** [comment]
Ugh, once again Brackets is hanging for me and I have to force quit it. Again.

**Comment by cfjedimaster** [comment]
Well, I've tried requiring a copy of lodash and it doesn't seem to help.

**Comment by 6ix** [comment]
I'm seeing this issue as well now ever since I updated to the latest this morning.

**Comment by cfjedimaster** [comment]
Yeah, I don't think we need anyone else to confirm it. ;)

**Comment by redmunds** [comment]
The lodash in Brackets () is 2.4.1, so you can use:

```js
var _ = brackets.getModule("thirdparty/lodash");
```

**Comment by cfjedimaster** [comment]
Didn't seem to work. I did it in main.js, right before I load jshint:

    var _ = brackets.getModule("thirdparty/lodash");
    require("jshint/jshint");


On Mon, Jun 1, 2015 at 3:25 PM, Randy Edmunds <notifications@github.com>
wrote:

> The lodash in Brackets () is 2.4.1, so you can use:
>
> var _ = brackets.getModule("thirdparty/lodash");
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/brackets-jshint/issues/81#issuecomment-107696289>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by catdad** [comment]
I spent an hour or two tonight trying for a workaround. No success.

For anyone in this thread that is stuck and hasn't figured it out yet, use this URL to load the older version of this extension:
https://s3.amazonaws.com/extend.brackets/camden.jshint/camden.jshint-2.2.15.zip

Since jshint/jshint#2330 basically says "sit tight, we are trying to figure out how to write tests", would you consider rolling JSHint back to 2.7.0 until they fix this issue?

**Comment by cfjedimaster** [comment]
yeah

On Mon, Jun 1, 2015 at 8:38 PM, Kiril Vatev <notifications@github.com>
wrote:

> I spent an hour or two tonight trying for a workaround. No success.
>
> For anyone in this thread that is stuck and hasn't figured it out yet, use
> this URL to load the older version of this extension:
>
> https://s3.amazonaws.com/extend.brackets/camden.jshint/camden.jshint-2.2.15.zip
>
> Since jshint/jshint#2330 <https://github.com/jshint/jshint/issues/2330>
> basically says "sit tight, we are trying to figure out how to write tests",
> would you consider rolling JSHint back to 2.7.0 until they fix this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/brackets-jshint/issues/81#issuecomment-107769023>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by cfjedimaster** [comment]
Wow, so this is epic. Brackets debug window won't render the console
anymore. It is still failing for me, but I can't figure out why since
Bracket's refuses to render the console now.

On Mon, Jun 1, 2015 at 8:44 PM, Raymond Camden <raymondcamden@gmail.com>
wrote:

> yeah
>
> On Mon, Jun 1, 2015 at 8:38 PM, Kiril Vatev <notifications@github.com>
> wrote:
>
>> I spent an hour or two tonight trying for a workaround. No success.
>>
>> For anyone in this thread that is stuck and hasn't figured it out yet,
>> use this URL to load the older version of this extension:
>>
>> https://s3.amazonaws.com/extend.brackets/camden.jshint/camden.jshint-2.2.15.zip
>>
>> Since jshint/jshint#2330 <https://github.com/jshint/jshint/issues/2330>
>> basically says "sit tight, we are trying to figure out how to write tests",
>> would you consider rolling JSHint back to 2.7.0 until they fix this issue?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cfjedimaster/brackets-jshint/issues/81#issuecomment-107769023>
>> .
>>
>
>
>
> --
> ===========================================================================
> Raymond Camden, Developer Advocate for MobileFirst at IBM
>
> Email : raymondcamden@gmail.com
> Blog : www.raymondcamden.com
> Twitter: raymondcamden
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by cfjedimaster** [comment]
Yeah, I give up. (Well, I want to give up.) I've closed Brackets and
restarted now about 5 times. It still fails, but I don't know why now.

On Mon, Jun 1, 2015 at 8:47 PM, Raymond Camden <raymondcamden@gmail.com>
wrote:

> Wow, so this is epic. Brackets debug window won't render the console
> anymore. It is still failing for me, but I can't figure out why since
> Bracket's refuses to render the console now.
>
> On Mon, Jun 1, 2015 at 8:44 PM, Raymond Camden <raymondcamden@gmail.com>
> wrote:
>
>> yeah
>>
>> On Mon, Jun 1, 2015 at 8:38 PM, Kiril Vatev <notifications@github.com>
>> wrote:
>>
>>> I spent an hour or two tonight trying for a workaround. No success.
>>>
>>> For anyone in this thread that is stuck and hasn't figured it out yet,
>>> use this URL to load the older version of this extension:
>>>
>>> https://s3.amazonaws.com/extend.brackets/camden.jshint/camden.jshint-2.2.15.zip
>>>
>>> Since jshint/jshint#2330 <https://github.com/jshint/jshint/issues/2330>
>>> basically says "sit tight, we are trying to figure out how to write tests",
>>> would you consider rolling JSHint back to 2.7.0 until they fix this issue?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/cfjedimaster/brackets-jshint/issues/81#issuecomment-107769023>
>>> .
>>>
>>
>>
>>
>> --
>>
>> ===========================================================================
>> Raymond Camden, Developer Advocate for MobileFirst at IBM
>>
>> Email : raymondcamden@gmail.com
>> Blog : www.raymondcamden.com
>> Twitter: raymondcamden
>>
>
>
>
> --
> ===========================================================================
> Raymond Camden, Developer Advocate for MobileFirst at IBM
>
> Email : raymondcamden@gmail.com
> Blog : www.raymondcamden.com
> Twitter: raymondcamden
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by cfjedimaster** [comment]
Reverted back to 2.6.3
