### ISSUE TITLE
Use `JsHint` instead of `JSHint` in brackets.json settings file ?

### ISSUE THREAD

**Issue by michaelrambeau** [cfjedimaster/brackets-jshint#83]
Hello,
I use Brackets 1.4 on Windows7.
I was not able to make jshint work until I made a change in the global "Preference File" (menu Debug > Open Preference file).
I use 'JsHint' instead of 'JSHint' here:

```js
    "language": {
      "javascript": {
          "linting.prefer": "JsHint",
          "linting.usePreferredOnly": true
      }
```
I am not sure if it is the right solution (should README.md be updated ?) or if I missed something.
Thank you for your attention.

**Comment by cfjedimaster** [comment]
Hmm - so I'm confused. That setting just tells Brackets to ignore JSLint and prefer JSHint. Are you saying that part didn't work, or the extension didn't work at all?

**Comment by busykai** [comment]
@michaelrambeau, works for me with capital "S" and *does not* work with the lower-case "s". If you try the array syntax for `linting.prefer`:
```json
    "language": {
      "javascript": {
          "linting.prefer": [ "JSHint" ],
          "linting.usePreferredOnly": true
      }
    }
```
then after you type the opening `[` after `"linting.prefer": `, in Brackets 1.4, you should get hinted on the currently registered `CodeInspection` providers. This extension registers a provider with upper-case "S", i.e. "JSHint".

P.S. FWIW, your example does not close the "language" brace, but I guess you just copied it like that.

**Comment by michaelrambeau** [comment]
Sorry for the late response, I should have included screenshots since the start.

What I mean is that with `"linting.prefer": "JSHint"` setting, linting feature is not enabled.
For example, there is no icon displayed at the right bottom corner, to show that my code is valid.
For example, I cannot see that my gulpfile.js is valid:

![image](https://cloud.githubusercontent.com/assets/5546996/9158438/0507b0ac-3f52-11e5-8d39-b638bafd329c.png)


But if I use `"linting.prefer": "JsHint"`, then linting is enabled and I can see the green check icon.

![image](https://cloud.githubusercontent.com/assets/5546996/9158460/3c047860-3f52-11e5-96f8-c6b38ca3eaaa.png)

@busykai I tried the array syntax but I got the same result.
And the missing brace was just the result of a "lazy" copy-paste, indeed.

Anyway, there may be something wrong with my settings if I was the only one with this problem, so don't mention this "issue" it and feel free to close it.
Thank you very much!

**Comment by cfjedimaster** [comment]
I think you need to use an array. Mine is: "linting.prefer":["JSHint"]

**Comment by michaelrambeau** [comment]
Hello, it seems to be a version problem.
If I install the extension from Brackets Extension Manager, I got the version 0.0.2

![image](https://cloud.githubusercontent.com/assets/5546996/9186953/13e900bc-4006-11e5-86d8-12cbdd059ce4.png)


In this old version, the linter is registered under the name `JsHint`, as I can see in main.js file: 

```
CodeInspection.register("javascript", {
    name: "JsHint",
    scanFile: hintFile
  });`
```

But if I check the code from the master branch, the name is `JSHint`, as you can see here:
https://github.com/cfjedimaster/brackets-jshint/blob/master/main.js#L38

So I don't know why I get an old version when I use Brackets Extension Manager (with Bracket 1.4 on Windows 7). I removed and re-installed the extension but I got the version 0.0.2 again.

**Comment by cfjedimaster** [comment]
Oh dude - that isn't me. TodorCampean is someone else.

**Comment by michaelrambeau** [comment]
Hello, hum, that is embarrassing, I am sorry for having spoiled your time.
What is confusing is that [brackets homepage](http://brackets.io/) includes a link to your `brackets-jshint` extension, in the "Popular extensions" category.
But when you use Brackets extension manager, if you search `brackets-jshint` you find "the other one", and I cannot see yours.
So I am wondering what is the right way to install your brackets-jshint extension (`git clone` in the brackets extension folder, I guess), maybe it could be mentioned in the README.md.
Anyway, thank you very much for your answers!

**Comment by cfjedimaster** [comment]
Just search for jshint and you will see mine.

On Tue, Aug 11, 2015 at 5:37 PM, Michael Rambeau <notifications@github.com>
wrote:

> Hello, hum, that is embarrassing, I am sorry for having spoiled your time.
> What is confusing is that brackets homepage <http://brackets.io/>
> includes a link to your brackets-jshint extension, in the "Popular
> extensions" category.
> But when you use Brackets extension manager, if you search brackets-jshint
> you find "the other one", and I cannot see yours.
> So I am wondering what is the right way to install your brackets-jshint
> extension (git clone in the brackets extension folder, I guess), maybe it
> could be mentioned in the README.md.
> Anyway, thank you very much for your answers!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/brackets-jshint/issues/83#issuecomment-130111941>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by michaelrambeau** [comment]
You are 100% right, it works. Thank you very much for your support!
