### ISSUE TITLE
Can't undo after save

### ISSUE THREAD

**Issue by ianbroad** [cfjedimaster/brackets-jshint#86]
When this extension is enabled, I cannot undo my edits immediately after I save.

**Comment by cfjedimaster** [comment]
This extension is using the linting API so it is nothing that I have control over. Asfar as I know, this would be an issue with Brackets itself, not the extension.

**Comment by glepretre** [comment]
@ianbroad @cfjedimaster Here's the brackets issue : https://github.com/adobe/brackets/issues/11826 :wink:

**Comment by cfjedimaster** [comment]
Thanks!
