### ISSUE TITLE
Globals no longer recognized with Brackets 1.9

### ISSUE THREAD

**Issue by wmurphyrd** [cfjedimaster/brackets-jshint#90]
After updating Brackets to v.1.9, JSHint started giving messages that require, MouseEvent, and CustomEvent are used without being defined. 

I tried uninstalling and reinstalling the add-on. Issue persists

**Comment by cfjedimaster** [comment]
Is this not a real issue though?

**Comment by wmurphyrd** [comment]
Oh man I don't know; I am new to js. Just thought you'd want to know about a behavior change. Feel free to close.

**Comment by cfjedimaster** [comment]
Sorry - my comment may have implied you were wrong to report this - what I mean is - aren't those really things that should be reported by jshint?
