### ISSUE TITLE
JSHint 2.10.1

### ISSUE THREAD

**Issue by brainwind-software** [cfjedimaster/brackets-jshint#91]
Hi,
thx for this great project !

Will you update it to JSHint 2.10.1 in the near future ?
Cause 2.10.1 now supports async/await also, which I and I guess a lot of others would love to see.

**Comment by cfjedimaster** [comment]
I'm not working on Brackets extensions anymore but I'd accept a PR for it.

**Comment by Smugger21** [comment]
So, I was able to patch it, I will make a pull request. So I can get this update.
